name: 生成 UnityAds Dylib

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest 
    steps:
      - name: 📥 取得程式碼
        uses: actions/checkout@v4

      - name: 🛠️ Setup Theos (Pro 級加速)
        uses: theos/setup-theos@master
        with:
          # 只抓取我們需要的 SDK 版本，速度提升 100 倍！
          sdk: 'iPhoneOS14.5'

      - name: 🚀 開始編譯 (Make)
        run: |
          # 自動生成 Swift 鑰匙
          touch Dummy.swift
          
          make clean
          make
        env:
          # 使用 setup-theos 自動配置好的路徑
          THEOS: ${{ env.THEOS }}

      - name: 📦 打包並交出 Dylib 檔案
        uses: actions/upload-artifact@v4
        with:
          name: UnityAds_Compiled_Dylib
          path: .theos/obj/debug/*.dylib
